export const AGREGA_PRODUCTOS = 'AGREGA_PRODUCTOS';
export const AGREGA_PRODUCTOS_EXITO = 'AGREGA_PRODUCTOS_EXITO';
export const AGREGA_PRODUCTOS_ERROR = 'AGREGA_PRODUCTOS_ERROR';

export const OBTIENE_PRODUCTOS = 'OBTIENE_PRODUCTOS';
export const OBTIENE_PRODUCTOS_EXITO = 'OBTIENE_PRODUCTOS_EXITO';
export const OBTIENE_PRODUCTOS_ERROR = 'OBTIENE_PRODUCTOS_ERROR';

