export const AGREGA_PRODUCTOS = 'AGREGA_PRODUCTOS';
export const AGREGA_PRODUCTOS_EXITO = 'AGREGA_PRODUCTOS_EXITO';
export const AGREGA_PRODUCTOS_ERROR = 'AGREGA_PRODUCTOS_ERROR';

export const OBTIENE_PRODUCTOS = 'OBTIENE_PRODUCTOS';
export const OBTIENE_PRODUCTOS_EXITO = 'OBTIENE_PRODUCTOS_EXITO';
export const OBTIENE_PRODUCTOS_ERROR = 'OBTIENE_PRODUCTOS_ERROR';

export const OBTIENE_PRODUCTO_ELIMINAR = 'OBTIENE_PRODUCTO_ELIMINAR';
export const ELIMINA_PRODUCTO_EXITO = 'ELIMINA_PRODUCTO_EXITO';
export const ELIMINAR_PRODUCTO_ERROR = 'ELIMINA_PRODUCTO_ERROR';

